version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/banorte_credito
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo_data:
